language: go

go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"

before_install:
  - go get -u golang.org/x/lint/golint
  - go get github.com/stretchr/testify

script:
  - make lint
  - 'if [[ "$TRAVIS_GO_VERSION" =~ ^1\.13 ]]; then GO111MODULE=on go mod download; else go get github.com/golang/dep/cmd/dep && dep ensure -v -vendor-only; fi'
  - ./test.sh
   
after_success:
  - bash <(curl -s https://codecov.io/bash)
